name: moat

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - moat

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - moat

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - moat

volumes:
  postgres_data:

networks:
  moat:
    name: moat
